global:
  scrape_interval: 1m  # default 1m 
  scrape_timeout: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['host.docker.internal:9090']

  - job_name: 'fast-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          app: FastAPI
          runtime: container

  - job_name: 'fast-api-local'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8000']
        labels:
          app: FastAPI
          runtime: localhost

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://prometheus.io/blog
        - http://fail.io/health
        - https://google.com
        - https://www.telegraph.co.uk

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.56.3:9115

  - job_name: "blackbox-icmp"
    metrics_path: "/probe"
    params:
      module: [ "icmp" ]
    static_configs:
      - targets: ["localhost", "8.8.8.8", "192.168.56.3", "10.175.62.21"]
    relabel_configs:
      - source_labels: [ "__address__" ]
        target_label: "__param_target"
      - source_labels: [ "__param_target" ]
        target_label: "instance"
      - target_label: "__address__"
        replacement: "192.168.56.3:9115"

  - job_name: 'blackbox-dns-monitor'
    scrape_interval: 1m
    metrics_path: /probe
    static_configs:
      - targets:
        - www.microsoft.com:8.8.8.8
        - www.google.com:1.1.1.1

    relabel_configs:
    # Populate domain label with domain portion of __address__
    - source_labels: [__address__]
      regex: (.*):.*$
      replacement: $1
      target_label: domain
    # Populate instance label with dns server IP portion of __address__
    - source_labels: [__address__]
      regex: .*:(.*)$
      replacement: $1
      target_label: instance
    # Populate module URL parameter with domain portion of __address__
    # This is a parameter passed to the blackbox exporter
    - source_labels: [domain]
      target_label: __param_module
    # Populate target URL parameter with dns server IP
    - source_labels: [instance]
      target_label: __param_target
    # Populate __address__ with the address of the blackbox exporter to hit
    - target_label: __address__
      replacement: "192.168.56.3:9115"


